### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils

### ISSUE THREAD

**Issue by Caosmaker** [assertthat/selenium-shutterbug#33]
Hi,
I've imported the jar in my project (automation test on varius site) btw when I call:
Shutterbug.shootPage(driver, ScrollStrategy.BOTH_DIRECTIONS).save();

i receive that errors:
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
	at com.assertthat.selenium_shutterbug.utils.file.FileUtil.getJsScript(FileUtil.java:32)
	at com.assertthat.selenium_shutterbug.utils.web.Browser.executeJsScript(Browser.java:193)
	at com.assertthat.selenium_shutterbug.utils.web.Browser.getDocWidth(Browser.java:161)
	at com.assertthat.selenium_shutterbug.utils.web.Browser.takeScreenshotEntirePage(Browser.java:82)
	at com.assertthat.selenium_shutterbug.core.Shutterbug.shootPage(Shutterbug.java:98)
	at com.assertthat.selenium_shutterbug.core.Shutterbug.shootPage(Shutterbug.java:72)
	at com.assertthat.selenium_shutterbug.core.Shutterbug.shootPage(Shutterbug.java:58)

Can u explain why, so I can fix my code?

Thanks

**Comment by glib-briia** [comment]
Hi, Which version are you using?

**Comment by Caosmaker** [comment]
Hi, Sorry for this by i'm noob in Java. I solved with import some io Oracle
external jar and all' run ok!

Il 26 ott 2017 8:12 PM, "Glib Briia" <notifications@github.com> ha scritto:

**Comment by glib-briia** [comment]
Just wondering which version of shutterbug are you using? That might be a valid issue which needs fixing

**Comment by Caosmaker** [comment]
0.7

Il 26 ott 2017 8:38 PM, "Glib Briia" <notifications@github.com> ha scritto:

**Comment by glib-briia** [comment]
Closing, since seems like not an issue any more
