### ISSUE TITLE
Sutterbug with mobile

### ISSUE THREAD

**Issue by sridhar73-hub** [assertthat/selenium-shutterbug#60]
Hi,
   I tried shutterbug with web, it is working fine. I tried with android and ios, but i am getting the following error.
Session ID: 1fa95a27-8a33-45dd-a664-ceb47a0ed94e
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:231)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:485)
	at com.assertthat.selenium_shutterbug.utils.web.Browser.executeJsScript(Browser.java:266)
	at com.assertthat.selenium_shutterbug.utils.web.Browser.getViewportHeight(Browser.java:243)
	at com.assertthat.selenium_shutterbug.utils.web.Browser.takeScreenshotEntirePageUsingChromeCommand(Browser.java:182)
	at com.assertthat.selenium_shutterbug.utils.web.Browser.takeScreenshotEntirePage(Browser.java:119)
	at com.assertthat.selenium_shutterbug.core.Shutterbug.shootPage(Shutterbug.java:110)
	at com.assertthat.selenium_shutterbug.core.Shutterbug.shootPage(Shutterbug.java:72)
	at com.assertthat.selenium_shutterbug.core.Shutterbug.shootPage(Shutterbug.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)

**Comment by glib-briia** [comment]
Hi @sridhar73-hub ,

Could you please let us know the exact exception you are getting (you've added the cause to the description) and selenium/browse versions you are using?

**Comment by glib-briia** [comment]
HI @sridhar73-hub ,

Cound you please try downgrading shutterbug version to 0.6 and try with the following command Shutterbug.shootPage(driver, ScrollStrategy.BOTH_DIRECTIONS,500,true).save("/screenshots");

(updating save location to specific one you are using).

**Comment by glib-briia** [comment]
closing ticket due to inactivity
