### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils

### ISSUE THREAD

**Issue by preetgrazitti** [assertthat/selenium-shutterbug#67]
I am receiving the error when using shootElement method.

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
	at com.assertthat.selenium_shutterbug.utils.file.FileUtil.getJsScript(FileUtil.java:32)
	at com.assertthat.selenium_shutterbug.utils.web.Browser.executeJsScript(Browser.java:255)
	at com.assertthat.selenium_shutterbug.utils.web.Browser.scrollToElement(Browser.java:247)
	at com.assertthat.selenium_shutterbug.core.Shutterbug.shootElement(Shutterbug.java:149)
	at com.assertthat.selenium_shutterbug.core.Shutterbug.shootElement(Shutterbug.java:135)

**Comment by glib-briia** [comment]
What shutterbug version are you using?
Have you got commons-io on your classpath already?

If you are using maven could you do `mvn dependency:tree ` and post the output

**Comment by glib-briia** [comment]
closing due to inactivity
