### ISSUE TITLE
getting error while scrolling the webpage

### ISSUE THREAD

**Issue by vishruth143** [assertthat/selenium-shutterbug#8]
Hi All,

I have written the below code to scroll [https://www.flipkart.com/]

```
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import com.assertthat.selenium_shutterbug.core.Shutterbug;
import com.assertthat.selenium_shutterbug.utils.web.ScrollStrategy;

public class FlipKart_Shutterbug {

    public static void main(String[] args) {
        System.setProperty("webdriver.chrome.driver", "C:\\Eclipse\\Drivers\\chromedriver.exe");
        WebDriver driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.get("https://www.flipkart.com/");
        Shutterbug.shootPage(driver, ScrollStrategy.BOTH_DIRECTIONS).save("C:\\Users\\Vishvambruth JT\\Desktop\\Screen.jpg");
        driver.quit();
    }
}
```

The code scrolls the webpage till end and throw the below error:

```
Starting ChromeDriver 2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b) on port 22816
Only local connections are allowed.
Oct 08, 2016 2:13:14 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Oct 08, 2016 2:13:15 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Exception in thread "main" java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
    at com.assertthat.selenium_shutterbug.utils.web.Browser.getCurrentScrollY(Browser.java:134)
    at com.assertthat.selenium_shutterbug.utils.web.Browser.takeScreenshotEntirePage(Browser.java:81)
    at com.assertthat.selenium_shutterbug.core.Shutterbug.shootPage(Shutterbug.java:70)
    at com.assertthat.selenium_shutterbug.core.Shutterbug.shootPage(Shutterbug.java:45)
    at FlipKart_Shutterbug.main(FlipKart_Shutterbug.java:15)
```

I'm Using:
**Chrome Version:** Version 53.0.2785.143 m
**Selenium Version:** Version 3.0.0-beta4
**OS:** Win10 64 bit
**Java:** 1.8

**Comment by glib-briia** [comment]
Hi @vishruth143 ,

Failing since [this](https://github.com/assertthat/selenium-shutterbug/blob/master/src/main/resources/js/get-current-scrollY.js#L1) returns double, however in my understanding, it should not, since the returned value is already rounded number of pixels.

Checked on Win 7 with same Chrome and Selenium version - works fine. 

Could you please execute the following and send me the output:

```java
System.setProperty("webdriver.chrome.driver", "C:\\Eclipse\\Drivers\\chromedriver.exe");
WebDriver driver = new ChromeDriver();
driver.manage().window().maximize();
driver.get("https://www.flipkart.com/");
Browser browser = new Browser(driver);
System.out.println("Scroll before: " + browser.executeJsScript(Browser.CURRENT_SCROLL_Y_JS));
Shutterbug.shootPage(driver, ScrollStrategy.BOTH_DIRECTIONS).save();
System.out.println("Scroll after: " + browser.executeJsScript(Browser.CURRENT_SCROLL_Y_JS));
Shutterbug.shootPage(driver, ScrollStrategy.BOTH_DIRECTIONS).save("C:\\Users\\Vishvambruth JT\\Desktop\\Screen.jpg");
driver.quit();
```

**Comment by vishruth143** [comment]
Hi @glib-briia,

Please find the output below after executing the above code as you suggested.

```
Starting ChromeDriver 2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b) on port 5369
Only local connections are allowed.
Oct 11, 2016 1:22:12 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Oct 11, 2016 1:22:14 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Scroll before: 0
Exception in thread "main" java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
	at com.assertthat.selenium_shutterbug.utils.web.Browser.getCurrentScrollY(Browser.java:134)
	at com.assertthat.selenium_shutterbug.utils.web.Browser.takeScreenshotEntirePage(Browser.java:81)
	at com.assertthat.selenium_shutterbug.core.Shutterbug.shootPage(Shutterbug.java:70)
	at com.assertthat.selenium_shutterbug.core.Shutterbug.shootPage(Shutterbug.java:45)
	at ShutterBug.main(ShutterBug.java:44)

```

**Comment by glib-briia** [comment]
Could you please enclose the code which is throwing exception in try-catch block like below, so we can see the output of 'Scroll after' :

```java
System.setProperty("webdriver.chrome.driver", "C:\\Eclipse\\Drivers\\chromedriver.exe");
WebDriver driver = new ChromeDriver();
driver.manage().window().maximize();
driver.get("https://www.flipkart.com/");
Browser browser = new Browser(driver);
System.out.println("Scroll before: " + browser.executeJsScript(Browser.CURRENT_SCROLL_Y_JS));
try{
Shutterbug.shootPage(driver, ScrollStrategy.BOTH_DIRECTIONS).save("C:\\Users\\Vishvambruth JT\\Desktop\\Screen.jpg");
}catch(Exception ex){
 ex.printStackTrace();
}
System.out.println("Scroll after: " + browser.executeJsScript(Browser.CURRENT_SCROLL_Y_JS));
driver.quit();
```

And send me the output please.

**Comment by vishruth143** [comment]
Hi @glib-briia,

Today I tried to execute the code with and without try catch block but both worked just fine. I have no clue why from two days it didn't work and when I tried today it started working.

```
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import com.assertthat.selenium_shutterbug.core.Shutterbug;
import com.assertthat.selenium_shutterbug.utils.web.Browser;
import com.assertthat.selenium_shutterbug.utils.web.ScrollStrategy;

public class ShutterBug {
	public static void main(String[] args) {
		System.setProperty("webdriver.chrome.driver", "C:\\Eclipse\\Drivers\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("https://www.flipkart.com/");
		Browser browser = new Browser(driver);
		System.out.println("Scroll before: " + browser.executeJsScript(Browser.CURRENT_SCROLL_Y_JS));
		//try{		
			Shutterbug.shootPage(driver, ScrollStrategy.BOTH_DIRECTIONS).save("C:\\Users\\Vishvambruth JT\\Desktop\\Screen.jpg");
			//}catch(Exception ex){
				//ex.printStackTrace();
			//}
		System.out.println("Scroll after: " + browser.executeJsScript(Browser.CURRENT_SCROLL_Y_JS));
		driver.quit();
	}
}
```

**Output
![2016_10_12_02_48_25_239](https://cloud.githubusercontent.com/assets/21016972/19301733/8972791e-9026-11e6-9061-df01168c5adf.png)
**

```
Starting ChromeDriver 2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b) on port 37847
Only local connections are allowed.
Oct 12, 2016 2:47:57 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Oct 12, 2016 2:47:59 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Scroll before: 0
Scroll after: 7106
```

**Comment by vishruth143** [comment]
Finally I was able to reproduce the issue. Find the output with try catch block.

```
Starting ChromeDriver 2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b) on port 1488
Only local connections are allowed.
Oct 12, 2016 3:03:03 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Oct 12, 2016 3:03:05 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Scroll before: 0
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Long
	at com.assertthat.selenium_shutterbug.utils.web.Browser.getCurrentScrollY(Browser.java:134)
	at com.assertthat.selenium_shutterbug.utils.web.Browser.takeScreenshotEntirePage(Browser.java:81)
	at com.assertthat.selenium_shutterbug.core.Shutterbug.shootPage(Shutterbug.java:70)
	at com.assertthat.selenium_shutterbug.core.Shutterbug.shootPage(Shutterbug.java:45)
	at ShutterBug.main(ShutterBug.java:45)
Scroll after: 7103.33333333333
```

**Comment by glib-briia** [comment]
Hi @vishruth143 ,

Thank you. That's very interesting. I haven't thought that 

```java
document.documentElement.scrollTop, document.body.scrollTop
```
could return double value.

This issue requires fix.

**Comment by vishruth143** [comment]
Hi @glib-briia,

I could see the bug # 8 is closed now. Is there any new .jar file for this or "selenium-shutterbug-0.3.jar" will only contain the fix for this. Please suggest.

**Comment by glib-briia** [comment]
Hi @vishruth143,

Yes, that's correc v. 0.3 will contain the fix and I'm planning to make it live sometime on the weekend.
