### ISSUE TITLE
Unknown error: cannot focus element

### ISSUE THREAD

**Issue by vishruth143** [assertthat/selenium-shutterbug#9]
Hi All,

I have written the below code

```
import java.awt.Color;
import java.awt.Font;
import java.util.Date;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import com.assertthat.selenium_shutterbug.core.Shutterbug;

public class ShutterBug {

	public static void main(String[] args) {
		System.setProperty("webdriver.chrome.driver", "C:\\Eclipse\\Drivers\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("https://www.google.com/");
		WebElement googleLogo = driver.findElement(By.xpath(".//*[@id='hplogo']"));
		WebElement searchBtn = driver.findElement(By.xpath(".//*[@id='tsf']/div[2]/div[3]/center/input[1]"));
		WebElement searchBox = driver.findElement(By.xpath(".//*[@id='sb_ifc0']"));

		searchBox.sendKeys("Testing");

		Shutterbug.shootPage(driver)
	        .blur(searchBox)
	        .highlight(searchBtn)
	        .monochrome(googleLogo)
	        .highlightWithText(googleLogo, Color.blue, 3, "Monochromed logo",Color.blue, new Font("SansSerif", Font.BOLD, 20))
	        .highlightWithText(searchBox, "Blurred secret words")
	        .withTitle("Google home page - " + new Date())
	        .withName("home_page")
	        .withThumbnail(0.7)
			.save("C:\\Users\\Vishvambruth JT\\Desktop\\Screen.jpg");
	        driver.quit();
	}
}
```
But the code is failing with the below error:
```
Starting ChromeDriver 2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b) on port 32342
Only local connections are allowed.
Oct 09, 2016 1:33:03 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Oct 09, 2016 1:33:05 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Exception in thread "main" org.openqa.selenium.InvalidArgumentException: unknown error: cannot focus element
  (Session info: chrome=53.0.2785.143)
  (Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 78 milliseconds
Build info: version: 'unknown', revision: '3169782', time: '2016-09-29 10:24:50 -0700'
System info: host: 'LAPTOP-JUUNTJIC', ip: '10.0.0.112', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={chromedriverVersion=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b), userDataDir=C:\Users\VISHVA~1\AppData\Local\Temp\scoped_dir11416_8399}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=53.0.2785.143, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 7bf71af0c3983c11b1fb2417f703dad0
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:164)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:636)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:284)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:108)
	at ShutterBug.main(ShutterBug.java:23)
```

> **I'm Using:**
> **Chrome Version:** Version 53.0.2785.143 m
> **Selenium Version:** Version 3.0.0-beta4
> **OS:** Win10 64 bit
> **Java:** 1.8

**Comment by glib-briia** [comment]
Hi @vishruth143 ,

The issue you have raised is nothing to do with shutterbug code (filing at at ShutterBug.main(ShutterBug.java:23)). You are getting the exception above because of invalid locator for search box. 

Try using this one instead:

```java
 WebElement searchBox = driver.findElement(By.xpath(".//*[@id='lst-ib']"));
```
